sss.tomcat:
  build: ./sss.tomcat
  container_name: sss.tomcat
  log_driver: "json-file"
  ports:
   - "8081:8080"
sss.data:
  build: ./sss.data
  container_name: sss.data
  log_driver: "json-file"
sss:
  build: ./sss
  container_name: sss
  env_file:
   - sss.env
  log_driver: "json-file"
  volumes_from:
   - mysql.data
   - sss.data
   - sss.tomcat
  external_links:
   - mysql
  ports:
   - "8391:8390"