sss.data:
  image: learninglayers/sss.data:0.0.1
  container_name: sss.data
  log_driver: "json-file"
sss:
  image: learninglayers/sss:0.0.8
  container_name: sss
  env_file:
   - common.env
   - sss.env
  log_driver: "json-file"
  volumes_from:
   - sss.data
  links:
   - mysql
  ports:
   - "8080:8080"
  actions:
   - create_databases: [sss.env]
