sss.tomcat:
  image: learninglayers/sss.tomcat:0.0.1
  container_name: sss.tomcat
  log_driver: "json-file"
  ports:
   - "8081:8080"
sss.data:
  image: learninglayers/sss.data:0.0.1
  container_name: sss.data
  log_driver: "json-file"
sss:
  image: learninglayers/sss:0.0.2
  container_name: sss
  env_file:
   - services/socialsemanticserver/sss.env
  log_driver: "json-file"
  volumes_from:
   - mysql.data
   - sss.data
   - sss.tomcat
  links:
   - mysql
  ports:
   - "8391:8390"
  actions:
   - create_databases: [sss.env]
   
